using System;

namespace FMS_Model
{

    public class billIndex
    {
        public string JobNumber { get; set; }
        public string CustomName { get; set; }
        public string CustomTel { get; set; }
        public string BillDate { get; set; }
        public string BillCode { get; set; }
        public decimal BillType { get; set; }
        public string Comment { get; set; }
        public string AtypeId { get; set; }
        public string PtypeId { get; set; }
        public string BtypeId { get; set; }
        public string EtypeId { get; set; }
        public string KtypeId { get; set; }
        public string KtypeId2 { get; set; }
        public string IfCheck { get; set; }
        public string CheckE { get; set; }
        public decimal TotalMoney { get; set; }
        public decimal TotalQty { get; set; }
        public decimal TotalInMoney { get; set; }
        public decimal Tax { get; set; }
        public string szPeriod { get; set; }
        public string Explain { get; set; }
        public bool Draft { get; set; }
        public string RedWord { get; set; }
        public decimal OrderId { get; set; }
        public string WayBillCode { get; set; }
        public string Goodsnumber { get; set; }
        public string PackWay { get; set; }
        public string Tel { get; set; }
        public decimal preferencemoney { get; set; }
        public string AlertDay { get; set; }
        public string Assessor { get; set; }
        public string IfAudit { get; set; }
        public string Audit_explain { get; set; }
        public string DtypeId { get; set; }
        public string VipCardID { get; set; }
        public string KTypeID3 { get; set; }
        public string LinkMan { get; set; }
        public string LinkTel { get; set; }
        public string LinkAddr { get; set; }
        public string wxManID { get; set; }
        public string JieJianBillNumberID { get; set; }
        public string JieJianID { get; set; }
        public string BaoXiuBillNumberID { get; set; }
        public string BaoXiuID { get; set; }
        public string BuyDate { get; set; }
        public string Serial { get; set; }
        public decimal wxTotal { get; set; }
        public string ErrDes { get; set; }
        public string ifHideJieJian { get; set; }
        public string ifWX { get; set; }
        public string RATypeID { get; set; }
        public string OperationSort { get; set; }
        public string RepairMode { get; set; }
        public string Oil { get; set; }
        public string Mileage { get; set; }
        public string EpibolyItem { get; set; }
        public string OtherItem { get; set; }
        public string Status { get; set; }
        public string ManHourTotal { get; set; }
        public string ManHourTax { get; set; }
        public string ManHourTaxTotal { get; set; }
        public string PTypeTotal { get; set; }
        public string PTypeTax { get; set; }
        public string PTypeTaxTotal { get; set; }
        public string EpibolyTotal { get; set; }
        public string OtherTotal { get; set; }
        public string InPriceType { get; set; }
        public string IfBargainOn { get; set; }
        public string BTypeID1 { get; set; }
        public string QuickRepairBillID { get; set; }
        public string ManHourInsuranceTotal { get; set; }
        public string PTypeInsuranceTotal { get; set; }
        public string InvoiceMode { get; set; }
        public string InvoiceCode { get; set; }
        public string InsuranceStatus { get; set; }
        public string STypeID { get; set; }
        public decimal FromBillNumberID { get; set; }
        public bool CostSale { get; set; }
        public string repairtype { get; set; }
        public string bespokedate { get; set; }
        public string receptiondate { get; set; }
        public string completedate { get; set; }
        public string infactorydate { get; set; }
        public string factcompletedate { get; set; }
        public string receptionid { get; set; }
        public string unitsatrap { get; set; }
        public string sendperson { get; set; }
        public string ErrDescription { get; set; }
        public string epibolycosttotal { get; set; }
        public string preferencereason { get; set; }
        public string balancedate { get; set; }
        public string itemprincipal { get; set; }
        public string monitorprincipal { get; set; }
        public string billstate { get; set; }
        public string intendingkickback { get; set; }
        public string settlementkickback { get; set; }
        public string BackTypeId { get; set; }
        public string intendingtalkbackdate { get; set; }
        public string istalkbackover { get; set; }
        public string ifmulaccount { get; set; }
        public decimal vipczmoney { get; set; }
        public int otherinouttype { get; set; }
        public string czbeforetimes { get; set; }
        public string PosBillType { get; set; }
        public string TransportId { get; set; }
        public string IsFreightMoney { get; set; }
        public string FreightAddr { get; set; }
        public string FreightPerson { get; set; }
        public string FreightTel { get; set; }
        public string wctypeid { get; set; }
        public string ShareMode { get; set; }
        public string Uf1 { get; set; }
        public string Uf2 { get; set; }
        public string Uf3 { get; set; }
        public string Uf4 { get; set; }
        public string Uf5 { get; set; }
        public string DealBtypeId { get; set; }
        public string cid { get; set; }
        public decimal rate { get; set; }
        public decimal ntotalmoney { get; set; }
        public decimal ntotalinmoney { get; set; }
        public decimal npreferencemoney { get; set; }
        public decimal nvipczmoney { get; set; }
        public string atypeid1 { get; set; }
        public string billproperty { get; set; }
        public decimal ncompletetotal { get; set; }
        public bool isini { get; set; }
        public string ATID { get; set; }
        public decimal completetotal { get; set; }
        public bool IfCargo { get; set; }
        public string IfInvoice { get; set; }
        public decimal invoicemoney { get; set; }
        public decimal ninvoicemoney { get; set; }
        public string CustomCode { get; set; }
    }
}
